<a href="https://colab.research.google.com/github/ZekeThePitcher/Minor-Project/blob/main/deeplearningtest1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install kaggle

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
! mkdir ~/.kaggle

In [ ]:
! cp /content/drive/MyDrive/ColabNotebooks/Kaggle/kaggle.json ~/.kaggle/kaggle.json

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle datasets download abhishek/gpt2-output-data -f small-117M.train.csv

100% 337M/338M [00:15<00:00, 25.3MB/s]
100% 338M/338M [00:15<00:00, 23.1MB/s]


In [ ]:
! unzip small-117M.train.csv.zip

Archive:  small-117M.train.csv.zip
  inflating: small-117M.train.csv    


In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/small-117M.train.csv', nrows = 100000)

In [ ]:
data['ended'].value_counts()

True     54735
False    45265
Name: ended, dtype: int64

In [ ]:
data['text'][3]

'DoJ\'s scheduled attacks are started without E+W+S+N. The scope of these attacks is not yet clear. But they can be cancelled after three days, where they can affect all these fancy immune timers with not equal amounts of possible multiples and so on, which makes it difficult to avoid attacks where failures that happen ninety days are the norm. Allies trained to other-controlled Multicore and Monoprice Systems (monoprice against E+W+S+N, study will be taking place coming soon) should run for seven attacks which is what we will teach Jorg as soon as possible. If someone shows up before you, try all the plus checkers. Hordes:At least nine things are wrong one way or the other! Developed Quest Locations:Goth Mod Chapter 28: 02/28/2013Euro Alliance in MythologySpecial Promotional Quests: Dolog Report Chapter 15: 04/02/2013Dialogue ExtractionMissions: Moreover carrying on those same quests are multiples to get requests for other plansCold War spiders and butterflies complained.. causesHe wa

In [ ]:
! pip install sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 23.2 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=69cd36cfd144a075eb78e820bf797c27251e40ba3f3c83ec78c208ce176bbaed
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer

In [ ]:
model = SentenceTransformer('all-MiniLM-L6-v2')

.gitattributes:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

data_config.json:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

train_script.py:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [ ]:
sentence = data['text'][0]

In [ ]:
sent2 = model.encode(sentence)

In [ ]:
print(sent2)

[ 1.12144224e-01 -2.48346701e-02  6.29539266e-02  5.92893064e-02
  5.99023886e-02  1.30605446e-02  2.05667466e-02 -1.25624146e-02
  3.67156863e-02 -2.26558447e-02 -6.17654324e-02  2.33287700e-02
 -5.04653789e-02  5.29648066e-02 -3.23503539e-02 -4.68071848e-02
  9.06699151e-02 -6.73170015e-02 -3.12249567e-02 -2.90233623e-02
 -2.64199283e-02 -5.24800345e-02 -5.24077490e-02  9.17803496e-02
  1.06931664e-02 -1.56078823e-02  2.83557996e-02 -4.31479439e-02
 -1.27286371e-02 -1.73144434e-02 -1.20680995e-01  7.60534182e-02
 -3.43971401e-02  3.56363021e-02 -6.65012840e-03 -2.32885480e-02
  2.64212471e-02 -6.30959496e-02  4.79797982e-02 -1.67219955e-02
  9.61723700e-02 -1.96528323e-02  4.45328020e-02  5.06537706e-02
 -1.07802656e-02  4.34893358e-04  1.43512515e-02 -1.25035970e-03
 -8.16947892e-02  1.21149749e-01  8.59151557e-02 -2.80099697e-02
  8.40158388e-02 -4.21458595e-02 -5.73367719e-03  2.54550930e-02
 -4.28924784e-02 -2.74620987e-02 -3.88376648e-03  3.45438085e-02
 -4.71925773e-02 -1.34774

In [ ]:
sentence2 = data['text'][1]

In [ ]:
sent22 = model.encode(sentence2)

In [ ]:
sent22

array([-4.01550345e-02, -2.97725387e-02,  3.97952050e-02,  6.35858178e-02,
        5.14649674e-02,  6.23810291e-02, -3.50892358e-02, -1.95702352e-02,
       -1.19124137e-01,  6.21395111e-02, -4.69951611e-03, -5.71248494e-03,
       -1.02378324e-01, -3.23135108e-02, -3.66917178e-02,  5.91887049e-02,
        8.26320983e-03, -5.17330095e-02, -2.86459643e-02,  6.20348230e-02,
       -3.56897525e-02,  4.20456287e-03, -8.10000598e-02,  4.78627943e-02,
       -4.91086543e-02, -1.48576349e-02, -2.95513272e-02, -6.46253526e-02,
       -5.37605733e-02, -3.46418889e-03, -1.93633214e-02, -1.31300120e-02,
        3.39623615e-02,  6.35863543e-02,  2.61301994e-02,  8.09388682e-02,
        7.40116015e-02,  4.14963365e-02,  1.21901778e-03, -3.14542353e-02,
       -1.66633271e-03, -5.45077175e-02, -9.54659358e-02, -2.21347455e-02,
       -6.07615709e-03, -3.83533388e-02,  6.05834797e-02, -9.95181203e-02,
       -8.25727955e-02, -6.87442124e-02,  1.71620436e-02,  3.11887898e-02,
        4.84100953e-02, -

In [ ]:
sent2.shape

(384,)

In [ ]:
sent22.shape

(384,)

In [ ]:
from tqdm import tqdm

In [ ]:
tqdm.pandas(desc='Progress:')

In [ ]:
data_test = model.encode(data['text'][0])

In [ ]:
import numpy as np

In [ ]:
np.hsplit(data_test, data_test.size)

[array([0.11214422], dtype=float32),
 array([-0.02483467], dtype=float32),
 array([0.06295393], dtype=float32),
 array([0.05928931], dtype=float32),
 array([0.05990239], dtype=float32),
 array([0.01306054], dtype=float32),
 array([0.02056675], dtype=float32),
 array([-0.01256241], dtype=float32),
 array([0.03671569], dtype=float32),
 array([-0.02265584], dtype=float32),
 array([-0.06176543], dtype=float32),
 array([0.02332877], dtype=float32),
 array([-0.05046538], dtype=float32),
 array([0.05296481], dtype=float32),
 array([-0.03235035], dtype=float32),
 array([-0.04680718], dtype=float32),
 array([0.09066992], dtype=float32),
 array([-0.067317], dtype=float32),
 array([-0.03122496], dtype=float32),
 array([-0.02902336], dtype=float32),
 array([-0.02641993], dtype=float32),
 array([-0.05248003], dtype=float32),
 array([-0.05240775], dtype=float32),
 array([0.09178035], dtype=float32),
 array([0.01069317], dtype=float32),
 array([-0.01560788], dtype=float32),
 array([0.0283558], dtype=

In [ ]:
data['text'] = data['text'].progress_apply(lambda x: str(x))

Progress:: 100%|██████████| 100000/100000 [00:00<00:00, 433673.09it/s]


In [ ]:
data['text2'] = data['text'].progress_apply(lambda x:model.encode(x))

Progress:: 100%|██████████| 100000/100000 [4:21:56<00:00,  6.36it/s]


In [ ]:
store_data = data['text2']

In [ ]:
data2 = pd.DataFrame(data)

In [ ]:
data2[:10]

NameError: ignored

In [ ]:
type(data2['text2'][0])

numpy.ndarray

In [ ]:
split_data = pd.DataFrame(data2['text2'].tolist())

In [ ]:
data3 = pd.concat([data2, split_data], axis=1)

In [ ]:
data3[:10]

id                                               text  length  ended  \
0   1  is one of many that have been struggling with ...    1024  False   
1   2  refine. 135 SHARES Share Tweet\n\nIt is tumult...    1024  False   
2   3  The fate of a pig was not decided until now, b...    1024  False   
3   4  DoJ's scheduled attacks are started without E+...     795   True   
4   5  - Virginian Journal blog\n\nTHE PRESIDENT OF T...    1024  False   
5   6  4 Atheists, Not Scientists, Learned Negativity...    1024  False   
6   7  In a second hearing on Tuesday, U.S. District ...    1024  False   
7   8  Soviet microbattery (generally, 3 watts) or co...     227   True   
8   9  w...\n\nHK's promotion committee has been led ...     308   True   
9  10  STREAM UPDATE\n\nSUNDAY, January 27, 2017\n\nT...    1024  False   

                                               text2         0         1  \
0  [0.112144224, -0.02483467, 0.06295393, 0.05928...  0.112144 -0.024835   
1  [-0.040155035, -0.029772539, 0.039795205, 0.06... -0.040155 -0.029773   
2  [0.12914866, 0.041478947, 0.028065503, 0.03196...  0.129149  0.041479   
3  [-0.083624065, 0.058546934, 0.037817635, 0.029... -0.083624  0.058547   
4  [-0.040699326, 0.0036865233, 0.057337556, -0.0... -0.040699  0.003687   
5  [-0.036231276, -0.03877128, -0.008100616, 0.03... -0.036231 -0.038771   
6  [-0.10228519, 0.018905539, -0.11191846, -0.008... -0.102285  0.018906   
7  [-0.018107709, 0.035750467, -0.07682238, 0.067... -0.018108  0.035750   
8  [-0.08026541, 0.0035662923, 0.0031109035, -0.0... -0.080265  0.003566   
9  [-0.007184694, -0.03048526, 0.020202864, 0.011... -0.007185 -0.030485   

          2         3         4  ...       374       375       376       377  \
0  0.062954  0.059289  0.059902  ...  0.084198  0.012157  0.010347 -0.001909   
1  0.039795  0.063586  0.051465  ... -0.008494 -0.001888 -0.001198 -0.018533   
2  0.028066  0.031960  0.010417  ... -0.019327  0.036544 -0.045330  0.033543   
3  0.037818  0.029454  0.015685  ... -0.077354 -0.068553  0.014939 -0.048553   
4  0.057338 -0.037602  0.089345  ...  0.073939  0.025814 -0.045195  0.034519   
5 -0.008101  0.035167  0.087634  ...  0.013644 -0.018566 -0.026538 -0.028408   
6 -0.111918 -0.008524  0.016294  ...  0.107863 -0.042839 -0.035534 -0.026333   
7 -0.076822  0.067177 -0.065268  ... -0.048462  0.058663 -0.041884  0.037757   
8  0.003111 -0.044051  0.001328  ...  0.018841 -0.019329  0.026317  0.043337   
9  0.020203  0.011052  0.046775  ... -0.026301  0.024376 -0.061553 -0.009456   

        378       379       380       381       382       383  
0  0.068593  0.036979 -0.014276 -0.047814 -0.186423 -0.000642  
1 -0.172899  0.035925  0.080160  0.009349 -0.045357  0.073876  
2  0.035930 -0.012167 -0.004636 -0.000542  0.034905  0.063359  
3  0.014945  0.023252  0.042630 -0.121564 -0.094866 -0.005650  
4  0.072605 -0.031004 -0.063632  0.013665  0.056927 -0.038605  
5 -0.073103 -0.005651  0.113025 -0.041410 -0.023354 -0.013743  
6 -0.026853 -0.031211 -0.077494 -0.084864  0.077805 -0.048986  
7 -0.062202 -0.033019  0.010337 -0.129939 -0.012985 -0.025675  
8 -0.042077  0.014755 -0.006790 -0.069452  0.002149  0.062417  
9  0.001832 -0.118629 -0.054640 -0.091338 -0.012105  0.039150  

[10 rows x 389 columns]

In [ ]:
data4 = data3.drop(columns=['id', 'text', 'length', 'text2'])

In [ ]:
data4.head

<bound method NDFrame.head of        ended         0         1         2         3         4         5  \
0      False  0.112144 -0.024835  0.062954  0.059289  0.059902  0.013061   
1      False -0.040155 -0.029773  0.039795  0.063586  0.051465  0.062381   
2      False  0.129149  0.041479  0.028066  0.031960  0.010417  0.002107   
3       True -0.083624  0.058547  0.037818  0.029454  0.015685  0.002456   
4      False -0.040699  0.003687  0.057338 -0.037602  0.089345  0.037959   
...      ...       ...       ...       ...       ...       ...       ...   
99995  False -0.044501 -0.012775 -0.005327 -0.056673  0.118828  0.007655   
99996   True -0.034433  0.011353 -0.011370 -0.044034  0.112131 -0.034982   
99997   True -0.082428  0.043359 -0.021542 -0.012371  0.071400 -0.019798   
99998   True  0.049319  0.035972  0.023873 -0.025410  0.141851 -0.049379   
99999   True  0.045250  0.033856 -0.128073 -0.008907  0.091545 -0.010895   

              6         7         8  ...       374       

In [ ]:
from sklearn import preprocessing

In [ ]:
encoder = preprocessing.LabelEncoder()

In [ ]:
data4['ended'] = encoder.fit_transform(data4['ended'])

In [ ]:
data4[:10]

ended         0         1         2         3         4         5  \
0      0  0.112144 -0.024835  0.062954  0.059289  0.059902  0.013061   
1      0 -0.040155 -0.029773  0.039795  0.063586  0.051465  0.062381   
2      0  0.129149  0.041479  0.028066  0.031960  0.010417  0.002107   
3      1 -0.083624  0.058547  0.037818  0.029454  0.015685  0.002456   
4      0 -0.040699  0.003687  0.057338 -0.037602  0.089345  0.037959   
5      0 -0.036231 -0.038771 -0.008101  0.035167  0.087634  0.043605   
6      0 -0.102285  0.018906 -0.111918 -0.008524  0.016294  0.023388   
7      1 -0.018108  0.035750 -0.076822  0.067177 -0.065268 -0.005814   
8      1 -0.080265  0.003566  0.003111 -0.044051  0.001328  0.086353   
9      0 -0.007185 -0.030485  0.020203  0.011052  0.046775 -0.008651   

          6         7         8  ...       374       375       376       377  \
0  0.020567 -0.012562  0.036716  ...  0.084198  0.012157  0.010347 -0.001909   
1 -0.035089 -0.019570 -0.119124  ... -0.008494 -0.001888 -0.001198 -0.018533   
2 -0.051047  0.106573 -0.033472  ... -0.019327  0.036544 -0.045330  0.033543   
3  0.018189  0.007847  0.020765  ... -0.077354 -0.068553  0.014939 -0.048553   
4  0.002849 -0.039542  0.007706  ...  0.073939  0.025814 -0.045195  0.034519   
5 -0.010601  0.052479  0.005328  ...  0.013644 -0.018566 -0.026538 -0.028408   
6  0.031596  0.106883 -0.022427  ...  0.107863 -0.042839 -0.035534 -0.026333   
7 -0.021467  0.056003 -0.023876  ... -0.048462  0.058663 -0.041884  0.037757   
8  0.023659  0.028949 -0.030217  ...  0.018841 -0.019329  0.026317  0.043337   
9  0.053381  0.006372  0.028999  ... -0.026301  0.024376 -0.061553 -0.009456   

        378       379       380       381       382       383  
0  0.068593  0.036979 -0.014276 -0.047814 -0.186423 -0.000642  
1 -0.172899  0.035925  0.080160  0.009349 -0.045357  0.073876  
2  0.035930 -0.012167 -0.004636 -0.000542  0.034905  0.063359  
3  0.014945  0.023252  0.042630 -0.121564 -0.094866 -0.005650  
4  0.072605 -0.031004 -0.063632  0.013665  0.056927 -0.038605  
5 -0.073103 -0.005651  0.113025 -0.041410 -0.023354 -0.013743  
6 -0.026853 -0.031211 -0.077494 -0.084864  0.077805 -0.048986  
7 -0.062202 -0.033019  0.010337 -0.129939 -0.012985 -0.025675  
8 -0.042077  0.014755 -0.006790 -0.069452  0.002149  0.062417  
9  0.001832 -0.118629 -0.054640 -0.091338 -0.012105  0.039150  

[10 rows x 385 columns]

In [ ]:
path = '/content/drive/MyDrive/ColabNotebooks/data4-100000.csv'

In [ ]:
with open(path, 'w', encoding = 'utf-8-sig') as f:
  data4.to_csv(f)